### ISSUE TITLE
profiles can't be found

### ISSUE THREAD

**Issue by erenoglu** [hattwj/rainmaker#1]
Hi,
I'm trying to test this on windows although I know you did not support it yet. I have all prerequisites installed, qt4, yaml, python, ssh, etc. 
I cloned rainmaker repo to my profile directory and ran it. But I'm getting the following error, which I'm trying to debug with a python debugger but could not advance much. The "profiles" variable is never populated. I saw a .rainmaker directory in my profile directory and copied the config.yml  in it, but your readme states a directory named ".client/conf" which I don't understand where it shall be. 

in Any hints?

C:\Users\emree\Rainmaker>python src\watcher.py
Traceback (most recent call last):
  File "src\watcher.py", line 605, in <module>
    rain = Rainmaker(profile)
  File "src\watcher.py", line 515, in **init**
    self.profiles = self.config.profiles
AttributeError: 'str' object has no attribute 'profiles'

**Comment by hattwj** [comment]
Hi,

The conf.py file is the master template and isn't primarily intended for editing. You need to create a profile first. Try python rainmaker.py -c to create a profile. 

Best of luck, let me know how it goes. Be sure to check for updates every few weeks. Ill try to keep it stable.

----- Reply message -----

**Comment by erenoglu** [comment]
Hi,

Thanks, I think this was not documented anywhere, could I ask you to put
this info also in your website?

Do I need to put it in the .rainmaker directory?

Now, next question, I understand this will follow the files and trigger
sync in my local computer, but how will it trigger the sync when there is a
change in the remote server? Shouldn't one copy also work on server side?
 (ie multiple clients can change the server).

Thanks,
Br,
Emre

On Fri, Aug 31, 2012 at 6:15 AM, hattb notifications@github.com wrote:

> Hi,
> 
> The conf.py file is the master template and isn't primarily intended for
> editing. You need to create a profile first. Try python rainmaker.py -c to
> create a profile.
> 
> Best of luck, let me know how it goes. Be sure to check for updates every
> few weeks. Ill try to keep it stable.
> 
> ----- Reply message -----
> From: "erenoglu" notifications@github.com
> To: "hattwj/Rainmaker" Rainmaker@noreply.github.com
> Subject: [Rainmaker] profiles can&apos;t be found (#1)
> Date: Mon, Aug 27, 2012 4:06 PM
> Hi,
> 
> I'm trying to test this on windows although I know you did not support it
> yet. I have all prerequisites installed, qt4, yaml, python, ssh, etc.
> 
> I cloned rainmaker repo to my profile directory and ran it. But I'm
> getting the following error, which I'm trying to debug with a python
> debugger but could not advance much. The "profiles" variable is never
> populated. I saw a .rainmaker directory in my profile directory and copied
> the config.yml in it, but your readme states a directory named
> ".client/conf" which I don't understand where it shall be.
> 
> in Any hints?
> 
> C:\Users\emree\Rainmaker>python src\watcher.py
> 
> Traceback (most recent call last):
> 
> File "src\watcher.py", line 605, in
> 
> rain = Rainmaker(profile)
> 
> File "src\watcher.py", line 515, in init
> 
> self.profiles = self.config.profiles
> 
> AttributeError: 'str' object has no attribute 'profiles'
> 
> &mdash;
> 
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hattwj/Rainmaker/issues/1#issuecomment-8180762.

## 

Emre

**Comment by hattwj** [comment]
I will be implementing updates from the server soon, ill be sure to let you know when it is ready.

**Comment by erenoglu** [comment]
OK great! Looking forward to testing it!

On Tue, Sep 11, 2012 at 6:50 PM, hattb notifications@github.com wrote:

> I will be implementing updates from the server soon, ill be sure to let
> you know when it is ready.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hattwj/Rainmaker/issues/1#issuecomment-8462688.

## 

Emre
